modLoader="javafml"
loaderVersion="[32,)"
issueTrackerURL="https://github.com/Tomson124/SimplyJetpacks2/issues"

[[mods]]
modId="simplyjetpacks"
version="${file.jarVersion}"
displayName="Simply Jetpacks 2"
updateJSONURL="https://github.com/Tomson124/SimplyJetpacks2/blob/1.16.x/updates/update.json"
displayURL="https://www.curseforge.com/minecraft/mc-mods/simply-jetpacks-2"
logoFile="assets/simplyjetpacks/simplyjetpacks-logo.png"
credits="cybercat5555"
authors="StormedPanda"
description='''
Simply Jetpacks 2

Previous Authors: Tomson124, tonius11
'''

[[dependencies.simplyjetpacks]]
    modId="forge"
    mandatory=true
    versionRange="[32,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.simplyjetpacks]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.1]"
    ordering="NONE"
    side="BOTH"
